apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: erwin-portal-internal-ldap-config-apply
spec:
  itemPath: "vaults/erwin-dev-portal/items/erwin-portal-internal-ldap-config-apply"